apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        name: mongo
      name: mongo-controller
    spec:
      selector:
        matchLabels:
          name: mongo
      template:
        metadata:
          labels:
            name: mongo
          name: mongo-controller
        spec:
          containers:
            - image: mongo
              name: mongo
              ports:
                - name: mongo
                  containerPort: 27017
              volumeMounts:
                - name: mongo-persistent-storage
                  mountPath: /data/db
          volumes:
            - name: mongo-persistent-storage
              persistentVolumeClaim:
                claimName: mongo-persistent-storage
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongo
      labels:
        name: mongo
    spec:
      ports:
        - port: 27017
          targetPort: 27017
      selector:
        name: mongo
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mongo-persistent-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-app
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: demo-app
      template:
        metadata:
          labels:
            app: demo-app
        spec:
          containers:
            - name: demo-app
              image: daniilkornilov/demo-app:1.0.0
              ports:
                - name: http
                  containerPort: 8081
                  protocol: TCP
              resources:
                requests:
                  memory: "180Mi"
                  cpu: "10m"
              env:
                - name: MONGO_INITDB_DATABASE
                  value: mydatabase
                - name: MONGO_INITDB_ROOT_PASSWORD
                  value: secret
                - name: MONGO_INITDB_ROOT_USERNAME
                  value: root
  - kind: Service
    apiVersion: v1
    metadata:
      name: demo-app
    spec:
      ports:
        - name: http-8081
          port: 8081
          protocol: TCP
          targetPort: 8081
      selector:
        app: demo-app
